### ISSUE TITLE
Use Map to navigate

### ISSUE THREAD

**Issue by Lucas-Gruber** [laurens94/vue-timeline-chart#12]
Hi, when i have an Timeline-Map (like in: [https://laurens94.github.io/vue-timeline-chart/examples/synced-timelines.html](https://laurens94.github.io/vue-timeline-chart/examples/synced-timelines.html))

How can I make it so that a user can grab the map group to navigate in the timeline?

**Comment by laurens94** [comment]
Hi! 
It's now possible (since `v2.2.0`) by using the `pointermove` event. 

I modified the example at https://laurens94.github.io/vue-timeline-chart/examples/synced-timelines.html so you can see how it's done.

Please let me know if this works for you! 😄

**Comment by Lucas-Gruber** [comment]
Thank you very much!
