### ISSUE TITLE
great work

### ISSUE THREAD

**Issue by giannik** [laurens94/vue-timeline-chart#6]
This looks great.
Does it support time spans down to minutes, seconds and milliseconds to use in video editing applications ?

**Comment by laurens94** [comment]
Thank you! 
It is definitely possible. For this you can use the `renderTimestampLabel` [prop](https://laurens94.github.io/vue-timeline-chart/reference/props.html) (it's a function) that determines what labels are rendered.

I made a simple example here:
https://laurens94.github.io/vue-timeline-chart/examples/custom-timestamp-labels.html
