### ISSUE TITLE
Feature request: adding down and up pointer events

### ISSUE THREAD

**Issue by zoranpopovic** [laurens94/vue-timeline-chart#9]
Thanks for a great component first of all.  I am wondering if it would be possible to expand the events beyond click event.  just pointer up and down events would enable sufficient event coverage to interactively extend the interval enpoints, and or shifting the interval along the timeline.

Many thanks.

**Comment by laurens94** [comment]
Hi! I'm glad that you like the component! :)
You can add any event listener by making sure the component has focus (add `tabindex="0"` to allow focus, and then click on it) and using the Vue event handlers, e.g.:

```vue
<Timeline
      tabindex="0"
      @keydown="customEventHandler($event)"
      @wheel="customEventHandler($event)"
/>
```
Let me know if this works out for you!

**Comment by zoranpopovic** [comment]
Thanks, yes I can do that, but I will not get the data on time location, not the potential item that event targeted.  Commuting those is complex, especially wrt zoom level, and would require replicating your internal code, etc.

**Comment by laurens94** [comment]
I see! I just added the new events.

**Comment by zoranpopovic** [comment]
Thank you so much, it works great. I'm using it to label video segments.

![output](https://github.com/laurens94/vue-timeline-chart/assets/10567525/dfa13aed-87e8-4d1e-98d3-f0a4fc19c0c1)

**Comment by zoranpopovic** [comment]
oh, the event type passed should be PointerEvent not MouseEvent

**Comment by laurens94** [comment]
fixed it!

**Comment by zoranpopovic** [comment]
thank you, the TS still complains though.  it looks like this part needs to change too:
```
    (e: 'pointerdown', value: { time: number; event: MouseEvent, item: TimelineItem | null }): void;
    (e: 'pointerup', value: { time: number; event: MouseEvent, item: TimelineItem | null }): void;
```

**Comment by laurens94** [comment]
Whoops of course, thanks. Should be alright now in `v2.1.2`!
